name: campusease_app
description: CampusEase - Your complete campus management app for a seamless college experience.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Supabase Backend
  supabase_flutter: ^2.8.3
  
  # State Management
  provider: ^6.1.2
  
  # Navigation
  go_router: ^14.6.2
  
  # Animations
  flutter_animate: ^4.5.2
  lottie: ^3.1.3
  shimmer: ^3.0.0
  
  # UI Components
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  iconsax: ^0.0.8
  google_fonts: ^6.2.1
  flutter_staggered_animations: ^1.1.1
  
  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.3.4
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  smooth_page_indicator: ^1.2.0+3
  fl_chart: ^0.70.2
  percent_indicator: ^4.2.3
  file_picker: ^10.3.8
  url_launcher: ^6.3.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hex_code"
    theme_color: "#hex_code"
